name: Revert Affiliate Tag

on:
  workflow_dispatch:

jobs:
  run-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repo
        uses: actions/checkout@v4

      - name: Instalar PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Rodar script SQL
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          psql "$DATABASE_URL" -f scripts/revert_affiliate_tag.sql